### ISSUE TITLE
Combine our efforts

### ISSUE THREAD

**Issue by daedalus28** [joaonuno/futil-js#1]
Hi there!

We've been building out a functional js lib with the same name at https://github.com/smartprocure/futil-js

Between our lib and lodash/fp, I think we've covered all the use cases you had here. If you're interested, I'd like to invite you to contribute to our lib to combine our efforts.

Also, since it's been a few years since you've updated this and it doesn't look maintained, would you mind releasing the `futil` package name on npm?

**Comment by daedalus28** [comment]
Also for reference, to release the package, just add us as the npm owner:

`npm owner add sp-dev futil`

**Comment by joaonuno** [comment]
Done.

**Comment by daedalus28** [comment]
Awesome, thanks!! We'll publish to the new package name soon! If you're interested in following the progress, we're tracking it in https://github.com/smartprocure/futil-js/issues/117

We'd love to have you contribute :smile:
